# Docker Compose file to set up a web application and a PostgreSQL database
services:
  web:
    build: .
    image: rubenhtun/devops-odyssey-app:v1.0
    ports:
      - "3000:5000"
    volumes:
      - ./:/app
    environment:
      - ENV_TYPE
      - DB_HOST
      - APP_COLOR

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
